version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: banco-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  banco-backend:
    build:
      context: ./banco-backend
      dockerfile: Dockerfile
    container_name: banco-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Otras variables
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

  banco-frontend:
    build:
      context: ./banco-frontend
      dockerfile: Dockerfile
    container_name: banco-frontend
    ports:
      - "4200:80"
    depends_on:
      - banco-backend
    restart: unless-stopped

volumes:
  pgdata:
